### ISSUE TITLE
Explore using covid.yapie.me as the backend

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#137]
## Description

I think we can explore using covid.yapie.me API instead of fetching and parsing the sheet using NodeJS every time we build the page, which slows down our build time.

If it is proven that using this API speeds up the build time and increase the data accuracy (due to the more frequent data update), we can merge the implementation of this issue to the `main` branch.

## Implementation Model

Fetch the data from covid.yapie.me in `getStaticProps` of the `ProvincesPage`.

### References & Context

- https://github.com/akane10/corona_sucks
- https://twitter.com/zainfathoni/status/1416662729448779783

## Tasks

- [ ] Fetch the data in `getStaticProps` of the `ProvincePage`
- [ ] Replace the data source from `wbw.json` to the API response of covid.yapie.me
- [ ] Use the `fetch-wbw` script as a fallback

**Comment by mazipan** [comment]
I think it's better to maintain our own API (if needed), just make sure we are aware with the API's availability when decide to use 3rd party API.

**Comment by zainfathoni** [comment]
Sounds good. Thanks for the suggestion Mas @mazipan.

I've been in touch with the creator of covid.yapie.me.
@adityapurwa will be consulting with him to improve our architecture and probably implementing our own API if necessary.
