### ISSUE TITLE
Migrate `/fetchers/*.js` files to TypeScript so we can share codes with the `/lib/*.ts` ones

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#144]
Yes, I can't simply export `lib/string-utils.ts` because of the language difference. 
Probably work if the configuration is updated or use additional library. But it'll take some time to explore and can affect the other part, so it'll be great if someone can help

__Originally posted by @ekamuktia in https://github.com/kawalcovid19/wargabantuwarga.com/pull/136#discussion_r671910801__

## Tasks

- [ ] Use `ts-node` instead of `node` to execute fetcher scripts.
- [ ] Add JSDoc types to all helper functions in fetcher files.
- [ ] Migrate all helper functions in fetcher files to `/lib/*.ts`.

**Comment by resir014** [comment]
Tasks list added.

**Comment by Namchee** [comment]
Can I work on this?

**Comment by zainfathoni** [comment]
Yes, of course.

According to [our contributing guidelines](https://kcov.id/wbw-contributing-guidelines), please create a draft pull request to signal the other contributors that you have started working on this issue, thanks, @Namchee!
