### ISSUE TITLE
Unit and Integration Tests Infrastructure

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#178]
## Overview

Thanks to our fellow contributors, this project grows fast in the past few days.
It's time to introduce a proper infrastructure for unit and integration tests.

This epic is blocking #294.

## References

You can refer to [this project](https://github.com/kentcdodds/jest-cypress-react-babel-webpack/blob/main/package.json) as an example.

## Current Tasks

- [x] #179
  - [x] [Jest](https://jestjs.io) as a test runner
  - [x] [Testing Library](https://testing-library.com) family of libraries as React test renderers
  - [x] ~[kcd-scripts](https://www.npmjs.com/package/kcd-scripts) for an easy testing scripts usage~
- [x] #180
- [x] Incorporate the `kcd-scripts` testing scripts in our workflows
  - [x] #181
  - [x] #182

**Comment by resir014** [comment]
@zainfathoni We should potentially also include Typescript + ESLint in the CI to catch any type/lint errors as well alongside unit tests.

**Comment by zainfathoni** [comment]
Shall we create another epic for the `.github/workflows/test.yml` file to contain everything needs to be done on the CI validation step @resir014? We can track some of these issues in that epic as well.

**Comment by resir014** [comment]
@zainfathoni I think we should expedite this issue.

Since we're getting a lot more tasks which needs unit/integration tests available (e.g. #197, #294) we should make this high-priority and shouldn't delay any further in implementing unit/integration tests.

**Comment by zainfathoni** [comment]
Agreed.
I'll work on it tonight.
