### ISSUE TITLE
Design system - Buttons

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/wargabantuwarga.com#212]
## Description

Expand our current button components for more customisability.

## Implementation Model

Buttons are currently taken from [Tailwind UI](https://tailwindui.com/components/application-ui/elements/buttons).

## Tasks

- [ ] Add White Button variant
- [ ] Expand each button's size options (xs, sm, md, lg, xl)
- [ ] Allow for rounded buttons
- [ ] Allow option to add icons in buttons (from Heroicons)

**Comment by hanihusam** [comment]
Can I help you with this one, Mas? @resir014

**Comment by zainfathoni** [comment]
Yes, as always Mas @hanihusam. There's no need to confirm.
As long as there's no existing Draft Pull Request, you can just create a Draft Pull Request and it will be yours to implement. 😉
