### ISSUE TITLE
Add Sentry Integration

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#22]
## Description

We need a way to capture runtime errors like #21.

## Implementation Model

KawalCOVID19 has a Sentry license that we can integrate with. Please let @zainfathoni know if you want to work on this issue.

Please bear in mind that the integration should be done while minimizing its impact on the Core Web Vitals.

## Tasks

- [ ] Prepare the Sentry project
- [ ] Implement the integration
- [ ] Ensure that there's no significant performance degradation in the Deployment Previews on Netlify

**Comment by kalwabed** [comment]
hey @zainfathoni, I think I can help with this.

**Comment by mazipan** [comment]
Do we still want to install Sentry @zainfathoni?

**Comment by zainfathoni** [comment]
> Do we still want to install Sentry @zainfathoni?

If we can do it without hurting the web performance, yes. But if not, I think we can forego it for now. 😅
