### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#236]
## Current Tasks

- [ ] 24
- [ ] 44
- [ ] 115
- [ ] 158
- [ ] 233
- [ ] 234

### Discussed in https://github.com/kawalcovid19/wargabantuwarga.com/discussions/147

<div type='discussions-op-text'>

<sup>Originally posted by **mazipan** July 19, 2021</sup>
This discussion is to grouping all about SEO ideas and suggestions.

Some of pending issues:

- [ ] https://github.com/kawalcovid19/wargabantuwarga.com/issues/24
- [ ] https://github.com/kawalcovid19/wargabantuwarga.com/issues/44
- [ ] https://github.com/kawalcovid19/wargabantuwarga.com/issues/115
- [ ] https://github.com/kawalcovid19/wargabantuwarga.com/issues/158
- [ ] #233 
- [ ] https://github.com/kawalcovid19/wargabantuwarga.com/issues/234</div>

**Comment by mazipan** [comment]
Top priority for now is #158

**Comment by mazipan** [comment]
Insights from @ekiriandra-seo

https://docs.google.com/document/d/1im7CF8XaF4yYQ_jJjjW7dOKZz8tJFvidtW7bOlqt1Y8/edit?usp=sharing
