### ISSUE TITLE
Update Open Graph Image using Hero Image

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#240]
## Description

Currently we use `https://wargabantuwarga.com/wbw.png` as our meta image in openGraph.

You can check the code in [pages/_app.tsx#L31](https://github.com/kawalcovid19/wargabantuwarga.com/blob/main/pages/_app.tsx#L31)

But in my opinion, the open graph image should be an image with a better info in it. I can see our hero image have a better information to be shared as our og:image.

![Screenshot_20210721-201242_Chrome](https://user-images.githubusercontent.com/7221389/126494349-02ea105a-9f7c-4f4b-9ff3-ffc71e4a2d04.jpg)

## Tasks

- [ ] Change the meta openGraph image using hero image. [Our Hero image](https://firebase-kanvas.imgix.net/warga_bantu_warga/hero_banner.png?w=720&q=70&auto=format,compress,enhance&fm=pjpg&cs=tinysrgb&fit=scale)
- [ ] You maybe need to change the height and width
- [ ] Test sharing to social media, FB and Twitter
  - [ ] https://cards-dev.twitter.com/validator
  - [ ] FB og validator
- [ ] Screenshot the result, attach on the PR
