### ISSUE TITLE
Static slug for province detail page

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#288]
## Description

Currently, we generate a slug based on the index and this can be changed everytime.

We need to set a static slug for this.

See the detail on the Doc on section 1.2.3:

https://docs.google.com/document/d/1im7CF8XaF4yYQ_jJjjW7dOKZz8tJFvidtW7bOlqt1Y8/edit?usp=sharing

## Tasks

- [ ] Generate slug from the `etc/fetcher`, slugify the title, e.g: `DKI Jakarta` will be `dki-jakarta`
- [ ] Use the slug on the client side, without any additional index
- [ ] Test the functionality

**Comment by ekamuktia** [comment]
Please consider this when setting the slug: 
- Some contacts have empty `penyedia` name like this one https://www.wargabantuwarga.com/provinces/dkijakarta-1/telemedicine-obat-gratis-80
- `penyedia` name may get updated

**Comment by ekamuktia** [comment]
My concern for this is the urls are already indexed by google or shared by user
Need to consider whether redirection from old url to new url is necessary

**Comment by zainfathoni** [comment]
> My concern for this is the urls are already indexed by google or shared by user
> 
> Need to consider whether redirection from old url to new url is necessary

I think we can afford losing the current index, since it's not that great, anyway. 😅
We can perform URL redirection using Netlify Redirect, but I think it is not worth the hassle.

**Comment by mazipan** [comment]
Try to find with this keywords `site:wargabantuwarga.com` and we will face many 404 in the search result.

It because the URLs are not stable.
It can be changed.

Since we still on the early phase in terms of SEO, it's better to fix now.
