### ISSUE TITLE
Static slug for contact detail page

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#289]
## Description

Related with #288 but for Contact Detail Page.

Currently, we generate a slug based on the index and this can be changed everytime.

We need to set a static slug for this.

See the detail on the Doc on section 1.2.3:

https://docs.google.com/document/d/1im7CF8XaF4yYQ_jJjjW7dOKZz8tJFvidtW7bOlqt1Y8/edit?usp=sharing

## Tasks

- [ ] Generate slug from the `etc/fetcher`, slugify the title, e.g: `3R Medika Gas` will be `3r-medika-gas`
- [ ] Use the slug on the client side, without any additional index
- [ ] Test the functionality

**Comment by ekamuktia** [comment]
Please consider this when setting the slug: 
- Some contacts have empty `penyedia` name like this one https://www.wargabantuwarga.com/provinces/dkijakarta-1/telemedicine-obat-gratis-80
- `penyedia` name may get updated

**Comment by mazipan** [comment]
Then we need to fallback to `keterangan`

**Comment by zainfathoni** [comment]
@all-contributors please add @ekiriandra-seo for ideas.
