### ISSUE TITLE
Revisit the search, to be served from the server

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#290]
## Description

See the detail on the Doc on section 1.2.1:

https://docs.google.com/document/d/1im7CF8XaF4yYQ_jJjjW7dOKZz8tJFvidtW7bOlqt1Y8/edit?usp=sharing

Currently our search feature are executed on the client side, the data is re-aggregated on the client.

Looking to our architecture that serve a static HTML, this should not happen, we have all the data. No need to re-calculate the data on the client side.

## Tasks

- [ ] Aggregate the data, filter and sort from the server side
- [ ] Show initial data without any re-aggregation
- [ ] Test the functionality

**Comment by zainfathoni** [comment]
Mas @famasya has built a demo over here.
https://famasya.github.io/wbw-gsheets-demo/

The backend is using TrustMedis' TypeSense instance.

This is the source code of the demo.
https://github.com/famasya/wbw-gsheets-demo

I'll be adding more details on how we can utilise this for our use case, but first I need to clarify some stuff from him, such as how often it updates the index from the latest updates in the Google Sheets.

**Comment by famasya** [comment]
Hi there, it is basically an open source version of Algolia. Fortunately typesense have [Algolia's instantsearch.js adapter](https://github.com/typesense/typesense-instantsearch-adapter) for faster development. 

Here's demo link for instantsearch.js with typesense server: https://famasya.github.io/wbw-gsheets-demo/

For the reindex, it happens on every 3 hours.

**Comment by zainfathoni** [comment]
I've prepared a public repository for this crawler project named [wbw-gsheets-crawler](https://github.com/kawalcovid19/wbw-gsheets-crawler).
Mas @famasya will help to set up the initial codebase later.

**Comment by famasya** [comment]
All set mas @zainfathoni . We have three indices for now:
- `wbw-gsheets-database`
- `wbw-gsheets-telemedicine`
- `wbw-gsheets-faq`

I'll send you typesense search key by PM

**Comment by zainfathoni** [comment]
Could you please help us to create a new `epic` issue for the integration with your search functionality, Mas @famasya?
Frankly, I don't know where it is hosted, how we can fetch the data, etc. 😅 🙏
