### ISSUE TITLE
Unique meta description for Province Detail Page

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#291]
## Description

Current Condition: (still using the default one)

Inisiatif warga untuk berbagi informasi seputar fasilitas kesehatan &amp; alat kesehatan untuk COVID-19. WargaBantuWarga memudahkan publik mencari &amp; mengakses informasi.

Suggestion:

Inisiatif warga untuk berbagi informasi seputar fasilitas kesehatan &amp; alat kesehatan untuk COVID-19 **di Provinsi Lampung**. WargaBantuWarga memudahkan publik mencari &amp; mengakses informasi

## Tasks

- [ ] Update on the `NextSeo` tag for `description` and `openGraph.description`
- [ ] Check the Netlify preview domain using https://seositecheckup.com/tools/google-search-results-preview-test
- [ ] Attach the result
