### ISSUE TITLE
Explore to utilize actions/cache for CI

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#308]
## Description

One of the long process in the CI is the installation process. From my observation, we have fetching Google sheet in it. 

I just think, can we just cache this `data` dir for the CI.

Since for the `type-check`, `lint`, etc usually doesn't need a real and updated data.

## Implementation Model

Maybe we can utilize `actions/cache@v1`

But this is an exploration ticket, we might can not ship it, but let's try it.

## Tasks

- [ ] Read the actions/cache@v1 docs
- [ ] Find a possibility to cache and restore `data` dir using it
- [ ] Test and capture a screenshot

**Comment by mazipan** [comment]
Or we can pass environment variables, like `CI=true` then we just create a dummy file data without calling the real data from Google sheets/docs

**Comment by zainfathoni** [comment]
> Or we can pass environment variables, like `CI=true` then we just create a dummy file data without calling the real data from Google sheets/docs

I think that's better. Let's use this approach instead.

**Comment by mazipan** [comment]
Close this ticket because we already take action on #372 which reduces our CI process time significantly
