### ISSUE TITLE
Kontak darurat page

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#325]
## UI Design

![image](https://user-images.githubusercontent.com/5663877/127277090-6c6b5934-96c3-4e00-8859-ba3c882d21cf.png)

![image](https://user-images.githubusercontent.com/5663877/127277063-8d423276-9ce7-4b3a-a3bb-7d197a518481.png)

![image](https://user-images.githubusercontent.com/5663877/127277127-cbd8fa0e-99f5-4feb-88e0-9567a5079b95.png)

## Implementation Model

Using Netlify Collection, we create the collection for the following sections:

- Contacts (list of name, description, image, and external link)
- Vaccine section (lists of text + external link)
- Oxygen section (lists of text + external link)

## Tasks

- [ ] Define Netlify CMS content structure
- [ ] Create Kontak Darurat page following the design in Figma
- [ ] Add Kontak Darurat CTA to homepage

**Comment by resir014** [comment]
Issue + tasks list updated.
