### ISSUE TITLE
Page Telemedicine

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#328]
## UI Design

**Widget**

![image](https://user-images.githubusercontent.com/5663877/127588529-2d8eac59-256d-4282-bd1a-72c40e6747f3.png)

**Page (TBA)**

![image](https://user-images.githubusercontent.com/5663877/127588561-3981a447-da45-4d7a-a67d-e627572fe05d.png)

## Implementation Model

Two implementation phases.

### Phase 1

We create a simple CTA on the homepage which directly links to the spreadsheet link here:

https://docs.google.com/spreadsheets/d/1gGnIiXmCcGpMkB_h98FiHW99uVdwcdTBq_GhIEl_4eM/edit?usp=sharing

### Phase 2

We implement a detailed page pulling data from the spreadsheet above.

The backend should be using #374.

## Tasks

Only partial tasks, need to be filled in further.

- [x] Telemedicine CTA on homepage #540
- [x] Update Telemedicine CTA on homepage to link to new Telemedicine page. #540
- [x] ~Implement Telemedicine page using Typesence backend~
- [x] #668

**Comment by mazipan** [comment]
The dummy page is live on [/telemedicine](https://www.wargabantuwarga.com/telemedicine)

But if we look in our homepage, for Telemedicine data actually consists of two sections, see screenshot:

![Screenshot_20210812-070458_Chrome](https://user-images.githubusercontent.com/7221389/129118914-a08d9ae2-ab22-464f-ac6c-93076a4c506e.jpg)

1. List of application supported by Kemenkes
2. List of doctycan be contacted directly

We already show data No.2 but not with No.1

What do you think @zainfathoni ?
I think we should complete the Figma Design also for this page.

**Comment by zainfathoni** [comment]
> The dummy page is live on [/telemedicine](https://www.wargabantuwarga.com/telemedicine)
> 
> But if we look in our homepage, for Telemedicine data actually consists of two sections, see screenshot:
> 
> ![Screenshot_20210812-070458_Chrome](https://user-images.githubusercontent.com/7221389/129118914-a08d9ae2-ab22-464f-ac6c-93076a4c506e.jpg)
> 
> 1. List of applications supported by Kemenkes
> 2. List of doctors can be contacted directly
> 
> We already show data No.2 but not with No.1
> 
> What do you think @zainfathoni ?
> I think we should complete the Figma Design also for this page.

I just addressed this concern in another issue at.

https://github.com/kawalcovid19/wargabantuwarga.com/issues/668#issuecomment-898159979

We can use a simple rich-text field represented in Markdown for the first iteration, then we can improve it after the design is ready.

**Comment by zainfathoni** [comment]
I just got a recent update from the designer that the new design for this section is ready.
Based on the design, we should keep it at the home page.

[Figma link](https://www.figma.com/file/XNNtIoFEdFqaXOee83n0oN/WBW?node-id=472%3A2939)

<img width="905" alt="Screenshot 2021-08-13 at 19 53 58" src="https://user-images.githubusercontent.com/6315466/129353376-47ba728a-5d9c-49bc-bdcb-684a123272b6.png">
