### ISSUE TITLE
Donasi Warga page + widget

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#329]
## UI Design

![image](https://user-images.githubusercontent.com/5663877/127584681-1da0b789-1b8c-4877-818d-c38930e1c6ef.png)

![image](https://user-images.githubusercontent.com/5663877/127584713-679dab12-c2c0-4ecf-b20f-2d9168175f2c.png)

## Implementation Model

To make this implementation quick, let's implement the widget with dummy data from JS first, before converting said dummy data into the final Netlify CMS collection.

## Tasks

- [ ] Create Donasi Warga widget on homepage with pulling dummy data from JS
- [ ] Create Donasi Warga page using said dummy data
- [ ] Convert JS dummy data into Netlify CMS collection
- [ ] Update page + widget to pull data from new Netlify CMS collection

**Comment by resir014** [comment]
Issues + task list updated.

**Comment by syauqy** [comment]
Hi mas @zainfathoni mas @resir014. Mas Resi going to work on this? I did a trial on the content layout using the existing `PageContent` and `HomePageContent`. I think the current `PageContent` is too tight for this cards.
![image](https://user-images.githubusercontent.com/3627108/127654300-abad9f26-6f94-497c-aeb3-91efae906da2.png)![image](https://user-images.githubusercontent.com/3627108/127656740-863cc775-c259-411a-946a-2b3a8a9b7293.png)

I also found one of the donation link [here](https://docs.google.com/spreadsheets/d/1u7N4rdfJ20yg7lrL7h0KnwbtZSjFXxkZqDZkcdib9fs/edit#gid=0) is broken (Donasi untuk satwa). Maybe the campaign is over I guess.

**Comment by mazipan** [comment]
@syauqy how is the progress?
I don't see any open PR related this ticket?

Since it's in our high priority board, maybe we can accelerate the progress.

**Comment by syauqy** [comment]
> @syauqy how is the progress?
> I don't see any open PR related this ticket?
> 
> Since it's in our high priority board, maybe we can accelerate the progress.

Hi @mazipan, sorry I haven't work on it. 
I thought it will be taken by Mas Resi. So, I worked on #515.
If it's okay, I will start working on this issue.

**Comment by mazipan** [comment]
About the broken link, can we get a confirmation @zainfathoni ?

**Comment by zainfathoni** [comment]
> About the broken link, can we get a confirmation @zainfathoni?

For the broken links, we're not supposed to show them anymore, because the campaign has ended.
FYI @syauqy, if you want to work on it.

**Comment by syauqy** [comment]
Sure mas @mazipan  @zainfathoni, I'll add a PR soon. 🙏 
Looks like the broken link is removed from the excel list.
