### ISSUE TITLE
Add commitizen on pre-commit hooks

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#345]
## Description

Standardize the commit message structure using https://github.com/commitizen/cz-cli

## Tasks

- [ ] Read the doc: https://github.com/commitizen/cz-cli
- [ ] Install all requirements as a devDependencies
- [ ] Add on the git pre-commit hooks
