### ISSUE TITLE
Migrate to typesense as search backend

### ISSUE THREAD

**Issue by famasya** [kawalcovid19/wargabantuwarga.com#374]
## Overview
As discussed at #290, we can move to typesense to gain instant-search capability. The search experience should be easier and faster for the user, as it provides typo-tolerant and near real-time search results.

### Implementation details
Typesense server will hosted by trustmedis and its contents are crawled hourly by [wbw-gsheets-crawler](https://github.com/kawalcovid19/wbw-gsheets-crawler). As discussed by @zainfathoni , there are three indices for now:
- `wbw-gsheets-database`
- `wbw-gsheets-faq`
- `wbw-gsheets-telemedicine`

More indices can be added by making MR into crawler repository.

Fortunately, we have [typesense-instantsearch-adapter](https://github.com/typesense/typesense-instantsearch-adapter) as a wrapper of Algolia's [instantsearch react components](https://github.com/algolia/react-instantsearch/). No need to write components from scratch.

Here's information of API KEY
<details><summary>CLICK ME</summary>
<pre>
HOST : public-api.trustmedis.id
PROTOCOL : https
PORT : 443
API KEY : FByczfHEjsTCihgkkYlq2YbAgUKMoyVP
<pre>
</details>

A dirty implementation to instantiate typesense class should be looked like:
```javascript
  const searchAdapter = new TypesenseInstantSearchAdapter({
    server: {
      apiKey: API_KEY, // search-only API key
      nodes: [
        {
          host: "public-api.trustmedis.id",
          port: "443",
          protocol: "https",
        },
      ],
    },
    additionalSearchParameters: {
      queryBy: ["pertanyaan" , "jawaban"], // for wbw-gsheets-faq index
    },
  });
```

## Current Tasks

- [ ] Develop proof-of-concept of searchbox using typesense (TS)
- [ ] Make TS components to be used across pages
- [ ] Implement TS components into "pusat data" page
- [ ] Implement TS components into "FAQ" page
- [ ] Implement TS components into "Telemedicine" page

**Comment by mazipan** [comment]
Just my two cents, the priority should be reordered.
Do not try to create a reusable component on the first place.
It will come into unnecessary complexity.

Just create for spesific page first, then we can think about centralized later.

**Comment by zainfathoni** [comment]
> Just my two cents, the priority should be reordered.
> Do not try to create a reusable component in the first place.
> It will come into unnecessary complexity, an early optimization.
> 
> Just create for any specific page first, then we can think about centralized later.

Agreed, Mas @mazipan. I have updated the task list accordingly.

Thank you for creating this epic with beneficial documentation, Mas @famasya!
I think we can treat #376 as a POC for this epic. That way, we don't waste any code further just for the sake of proofing the concept. 😁

**Comment by famasya** [comment]
Well, I've also written a quick implementation of this approach [in this commit](https://github.com/famasya/wargabantuwarga.com/commit/1ddd0a58ca4514a33ceef392d9d90675ae68bfff?branch=1ddd0a58ca4514a33ceef392d9d90675ae68bfff&diff=split) from this [`stateResults` reference](https://www.algolia.com/doc/api-reference/widgets/state-results/react/) mas @zainfathoni . Hope it helps.

PS: pardon for bad styling, :))

**Comment by resir014** [comment]
Friendly reminder that this issue **need to be expedited** due to the reasons mentioned in https://github.com/kawalcovid19/wargabantuwarga.com/issues/197#issuecomment-886702751: 

> Found more issues with `itemsjs`: turns out it's using a vulnerable version of lodash:
>
> ![image](https://user-images.githubusercontent.com/5663877/126996085-f2392f07-30e9-4a3e-8cb8-70dd7d86ba9b.png)
>
> A quick peek through the bundle analyser shows that it's coming from `itemsjs`. We missed out on this initially, because turns out the dependency is [inlined within itemsjs itself](https://github.com/itemsapi/itemsjs/tree/master/vendor):
>
> ![image](https://user-images.githubusercontent.com/5663877/126996174-37a487a2-f42f-41f1-99a2-326bfc1606c8.png)

cc: @zainfathoni @mazipan @ekamuktia @famasya

**Comment by mazipan** [comment]
I just don't think we need this kind of Search Library in the front-end 😂
But ya, from our previous decision we will go with the TypeSense.
Can we accelerate the progress?

**Comment by resir014** [comment]
Current progress is in #401 and #540. But unfortunately progress on these has kind of stagnated for a bit.

**Comment by mazipan** [comment]
We need to deliver one page, at least for a pilot.

**Comment by ekamuktia** [comment]
Sorry, I wasn't feeling well so I coudn't work on it. Just pushed #401 update. 
Basic feature is done, but I still have some problems on the setting & testing.

First, for the setting as I mentioned here https://github.com/kawalcovid19/wargabantuwarga.com/pull/401#issuecomment-888246450

And for testing, since the data is from index, mock data can't be initialized and passed as props. Tried to find mock for typesense/algolia but still can't find it so I change the test using hardcoded text -> could result in failed test if the data is updated.

**Comment by mazipan** [comment]
I think we need to add more developer to help @ekamuktia.

@zainfathoni can you help on the testing part once we get a full flow?

I will try to take a look the PR tomorrow, looking if I can help on this 😂

**Comment by zainfathoni** [comment]
Sure, I'll try to unblock the testing part later today. 👌
Thanks, Mbak @ekamuktia for implementing it this far. 😁🙏
