### ISSUE TITLE
Add badge to show our latest code coverage

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#375]
## Description

Since we have success submit our code coverage to codecov, we need to know the codecov status via badge in the readme.

## Tasks

- [x] Ask @zainfathoni to generate a badge via codecov settings
- [x] Or via shield.io `https://img.shields.io/codecov/c/github/kawalcovid19/wargabantuwarga.com` 
- [ ] Link the badge to codecov dashboard on `https://app.codecov.io/gh/kawalcovid19/wargabantuwarga.com`

Sample code:

```
[![Codecov](https://img.shields.io/codecov/c/github/kawalcovid19/wargabantuwarga.com)](https://app.codecov.io/gh/kawalcovid19/wargabantuwarga.com)
```

Sample badge:

[![Codecov](https://img.shields.io/codecov/c/github/kawalcovid19/wargabantuwarga.com)](https://app.codecov.io/gh/kawalcovid19/wargabantuwarga.com)

**Comment by zainfathoni** [comment]
This is the badge code:

```markdown
[![codecov](https://codecov.io/gh/kawalcovid19/wargabantuwarga.com/branch/main/graph/badge.svg?token=zFsEIQ4bhy)](https://codecov.io/gh/kawalcovid19/wargabantuwarga.com)
```

[![codecov](https://codecov.io/gh/kawalcovid19/wargabantuwarga.com/branch/main/graph/badge.svg?token=zFsEIQ4bhy)](https://codecov.io/gh/kawalcovid19/wargabantuwarga.com)

**Comment by mazipan** [comment]
**Mulai Aja Dulu**

Nanti juga **Pasti Ada Jalan**

Make it happen, make it better (asal jangan sampai lupa make it better nya aja ya)

**Comment by zainfathoni** [comment]
> **Mulai Aja Dulu**
> 
> Nanti juga **Pasti Ada Jalan**
> 
> Make it happen, make it better (asal jangan sampai lupa make it better nya aja ya)

Nice sales pitch! 😆
