### ISSUE TITLE
Refactor `Page` components to follow Website 2.0 design

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/wargabantuwarga.com#391]
## Implementation Model

This need a rework on how the Page components work. We need to separate `PageContent` to `HomePageContent` which is used specifically in the homepage. We also need to modify how the Card component works in the sense that 

## Tasks

- [x] Add `Container` component to design system
- [x] Separate container from the page components
- [x] Separate `PageContent` and `HomePageContent`
- [x] Create `HomePageSection` component
