### ISSUE TITLE
Enhance the category search and filter mechanism and UI to allow user act faster on the information provided there

### ISSUE THREAD

**Issue by baraeb92** [kawalcovid19/wargabantuwarga.com#421]
## Description

The current new UI for the province database creates several problems from the user's POV: 

(1) By hiding the filter within the filter button, makes the functionality less obvious, and the current design is also less intuitive for users because there's no submit category button, only dismiss. 

(2) Clicking enter on the search bar also send the user to the filter function instead submit the search query (which is not what the user intended to action)

(3) There's no quick way for the user to act on the action

## Implementation Model

As we change the outlook and strategy for WBW website to only use hotline as last resort for more scalable operations and better triage of problem, we need to put user's needs above the internal operational needs, thus might need to change the way we see how some features implemented on this page. (ie Salin features) 

## Tasks

- [ ] Remove the reset and sorting filter from the page
- [ ] Show the location and category filter on the page rather than hiding it within the filter button, also make sure that the location filter is showing the value of the province when the user already selecting provinces. (ie if user is looking at Bali database, then by default the location filter should show Bali instead of "Semua")
- [ ] Change filter button to search button instead
- [ ] Change the Salin button to Chat WhatsApp and Buka Peta button
- [ ] Add copy text or salin functionality as an icon after the address and phone number text. 

<img width="1062" alt="Screen Shot 2021-07-25 at 22 01 42" src="https://user-images.githubusercontent.com/23743497/126905305-a27ef8ba-1279-4cd7-a215-a85d692ae655.png">
<img width="312" alt="Screen Shot 2021-07-25 at 22 02 00" src="https://user-images.githubusercontent.com/23743497/126905307-ca7807be-c190-485f-8f24-c5d8dd7c3d4a.png">

**Comment by baraeb92** [comment]
Related issue: https://github.com/kawalcovid19/wargabantuwarga.com/pull/420

**Comment by resir014** [comment]
@baraeb92 I'm re-posting the rationale behind the UI change for the filter @zainfathoni and I did from the Slack over here.

The reason we decided to tweak the search and filter UI is because we had to make room for implementing a virtualised list for our `/provinces` list (#125). This is an important change performance-wise, since the bigger the number of lists that gets rendered on the page, the heavier it is on the user's load. However, this comes with a downside - for this to work, we had to implement static scrolling (that is, only the virtualised list gets scrolled), otherwise we would have double-scrolling, making the UI very janky indeed.

However, the current filter UI **takes up 2/3 of the screen**, meaning this will happen.

https://user-images.githubusercontent.com/5663877/126910964-5943cd58-9bb8-49fc-b650-78f8017f88d9.mp4

I'm okay with reverting the UI back to the previous one, _as long as_ we could find a way to make the filter option take less space. In case we need to make further performance improvements in the future, we need to make this feature ready.

**Comment by baraeb92** [comment]
Noted, thanks for the context @resir014 yes, the previous design can be improved as well. 

I already attached the wireframe to be used as consideration for the next enhancement. 

I believe the new design can help, because it actually take the same horrizontal phase as your implementation, maybe just a bit more. 

But definitely not as big as our previous implementation. 

This I think a good compromise between usability and screen real estate.

**Comment by zainfathoni** [comment]
> Change the Salin button to Chat WhatsApp and Buka Peta button

I have a few concerns about this:

1. Not all numbers are `WhatsApp`-able, are we sure to make them always to be linked to WhatsApp?
2. Some phone number fields contain multiple phone numbers, os it's much more complex to provide that functionality rather than a simple `Salin` button

**Comment by baraeb92** [comment]
I'm open for alternative solution. 

Alternatively we can keep the salin for phone number as it is but making sure that when user click on the phone number it will prompt call to phone number instead. 

And for data that has multiple phone number we can use comma to seperate each of them maybe with dedicated line instead? @zainfathoni ![Screenshot_20210726-094330_Contacts.jpg](https://user-images.githubusercontent.com/23743497/126925992-94af4a04-ae8a-4b31-960b-cc9673e3ff04.jpg)
