### ISSUE TITLE
Add more reference text in Rumah Sakit & Donor Plasma queries

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#453]
## Description

[Context](https://kawalcovid19.slack.com/archives/C0279E2Q99Q/p1627309956034600)

<img width="468" alt="Screenshot 2021-07-26 at 23 11 05" src="https://user-images.githubusercontent.com/6315466/127013329-05ed4c36-ae7d-47bd-bb33-2596bb0646fc.png">

![image](https://user-images.githubusercontent.com/6315466/127013388-e0532875-a90f-4c37-8218-10b191e03573.png)

![image](https://user-images.githubusercontent.com/6315466/127013412-95708a98-45ea-47ec-bddb-85a31a1d717f.png)

## Implementation Model

If the query params satisfy both cases above, show the requested text

## Tasks

- [ ] Implement the additional reference text in the `Provinces` Page
- [ ] Render the additional reference text based on the query params
- [ ] Write the unit tests

**Comment by ekafyi** [comment]
Something like this? @zainfathoni 

![Screen Shot 2021-07-26 at 22 43 23](https://user-images.githubusercontent.com/6597211/127018419-953dd601-5bc3-4404-9d18-6e5ebe6dfd3f.png)

if anyone else with a *less questionable* visual design sense than me has a different idea, please do chip in.

also summoning Komisaris Design System™ @resir014 in case there's an existing documented component that's more suitable for this.

**Comment by resir014** [comment]
@ekafyi That might work! We could use a [Well](https://tailwindui.com/components/application-ui/layout/panels#component-8d5f81c8e04bef91faf820f62e3026e8) component for that specific design. Or if that feels weird/we want to stick to any existing component, we could use an [Alert](https://tailwindui.com/components/application-ui/feedback/alerts).
