### ISSUE TITLE
Replace `eslint-plugin-simple-import-sort` w `eslint-plugin-import`

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#483]
## Description

Current `eslint-plugin-simple-import-sort` is problematic, it can prioritize internal code above the 3rd parties.

## Implementations

Fix the configs, or migrate to the new one

## Tasks for fix the config

- [ ] Need to play w this current config, maybe adding another regex

```js
"simple-import-sort/imports": [
  "warn",
  {
    "groups": [
      ["^.+\\.s?css$"],
      ["^\\u0000"],
      ["^react$"],
      ["^~"],
      ["^\\.\\.(?!/?$)", "^\\.\\./?$"],
      ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"]
    ]
  }
],
```

## Tasks for migration

- [ ] Read the [docs](https://github.com/import-js/eslint-plugin-import)
- [ ] Use the default set as mentioned in the docs

```js
'import/no-unresolved': [2, { commonjs: true, amd: true }],
'import/named': 2,
'import/namespace': 2,
'import/default': 2,
'import/export': 2
```

- [ ] Use along w ts import

```js
'plugin:import/recommended',
'plugin:import/typescript',
```

- [ ] Maybe you need to set the parser into TS, I don't know

```js
parser: '@typescript-eslint/parser'
```

- [ ] Run `lint:fix` to perform autofix for all dirs
