### ISSUE TITLE
Provide favicon without text

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#561]
## Description

Our icon on the repo ([see this image](https://github.com/kawalcovid19/wargabantuwarga.com/blob/main/public/wbw.png)) is have a text on the bottom of the icon.

IMO, favicon is better without any text, it also looks weird on the small pixel like in the Google Search Result.
It looks like we have a black line since the text is not readable.

### Assets

[Logo Assets](https://drive.google.com/drive/folders/1bfdW3SLk59XeNOr8txiEzHXljhGMwaYX)

## Tasks

- [x] Ask new alternative icon without text with dimensions at least 512x512
- [ ] Generate maskable icon in https://maskable.app/editor for safe icon on PWA
- [ ] Change the favicon meta
- [ ] Change favicon on manifest.json

**Comment by zainfathoni** [comment]
I just added the link to the [Logo Assets](https://drive.google.com/drive/folders/1bfdW3SLk59XeNOr8txiEzHXljhGMwaYX). Let me know if anybody trying to work on this issue can't access them.
