### ISSUE TITLE
Display the new `Ketersediaan` field from the database

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#600]
## Description

From now on, our database team has dedicated volunteers to update the availability of COVID-19-related services, such as **Oksigen**, **Tempat Isoman**, **Bantuan Kebutuhan Pokok**, and **Tempat Vaksin**.

We need to reflect the values from the last column (`Ketersediaan`) in the [database sheets](https://kcov.id/wbw-sheets) into our `Province` and `Contact` pages.

### Additional Context

[Slack thread](https://kawalcovid19.slack.com/archives/C0279E2Q99Q/p1627620878006200)

<img width="663" alt="Screenshot 2021-08-09 at 10 26 35" src="https://user-images.githubusercontent.com/6315466/128654706-ec20cf9a-7689-47fc-a91e-021298a9e31b.png">

### Data Source

Fetch the values from the last column in the [database sheets](https://kcov.id/wbw-sheets)

<img width="141" alt="Screenshot 2021-08-09 at 10 31 44" src="https://user-images.githubusercontent.com/6315466/128654939-d5d64f4e-a93a-4e73-a765-5be118b97b57.png">
<img width="148" alt="Screenshot 2021-08-09 at 10 31 29" src="https://user-images.githubusercontent.com/6315466/128655029-959feb8d-1ead-4271-b927-aa7172c0e9a5.png">

### `Province` Page

Add another tag besides the `Kebutuhan` tag.

- if `Tersedia`, add a `green` tag,
- else if `Tidak Tersedia`, add a `red` tag,
- else add nothing.

<img width="578" alt="Screenshot 2021-08-09 at 10 29 35" src="https://user-images.githubusercontent.com/6315466/128654849-d4c7de44-5a98-4fbf-b4e9-07b5c25eaf12.png">

### `Contact` Page

Add a new description row indicating `Ketersediaan`. Hide the row if it's empty.

<img width="613" alt="Screenshot 2021-08-09 at 10 36 49" src="https://user-images.githubusercontent.com/6315466/128655193-90d23e18-21fa-4f7c-97d3-46534d0ff378.png">

## Tasks

- [ ] Update the [fetch-sheets.ts](https://github.com/kawalcovid19/wargabantuwarga.com/blob/b190024d3beeba67a569149208b7c236f6d3e5ad/etc/fetchers/fetch-sheets.ts) implementation to add the last column
- [ ] Update the [Contact type definition](https://github.com/kawalcovid19/wargabantuwarga.com/blob/d51b003088004be1c72d35b33b962ed2e7b2e5ae/lib/data/provinces.ts#L12-L26)
- [ ] Render the new tag in the `Province` page accordingly
- [ ] Render the new row in the `Contact` page accordingly
- [ ] Fix the broken tests accordingly
- [ ] Write more tests to cover the newly introduced cases
