### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/wargabantuwarga.com#605]
## Overview

This is a master issue to track all security-related improvements to WBW.

Currently the WBW website is still missing some essential security headers, as detected by [securityheaders.com](https://securityheaders.com/?q=https%3A%2F%2Fwww.wargabantuwarga.com%2F&followRedirects=on)

![image](https://user-images.githubusercontent.com/5663877/128665607-14df3366-a57d-4576-9e4c-303b6582c87c.png)

## Current Tasks

- [ ] #482
- [ ] Prevent clickjacking with `X-Frame-Options: DENY` header
- [ ] Prevent content type sniffing with `X-Content-Type-Options: nosniff` header
- [ ] Add a `Permissions-Policy` header to disallow features that we don't use

**Comment by resir014** [comment]
![image](https://user-images.githubusercontent.com/5663877/129010905-20a7410a-25ca-43af-915d-1ae31ad95af5.png)

Thanks to the changes implemented here, our security score is now at A. 🎉 

However, we still need to implement proper security vulnerability reporting measures, as dictated by #482. Please direct all attentions for this epic to that issue from now on.

**Comment by resir014** [comment]
All of these tasks are done!

However, [Snyk](https://snyk.io/test/website-scanner/?test=210815_AiDcR8_6651aed4d892de601a87500eae1971a1) still gives us a security score of **B**, due to our use of Lodash, as mentioned [here](https://github.com/kawalcovid19/wargabantuwarga.com/issues/374#issuecomment-894809240):

![image](https://user-images.githubusercontent.com/5663877/129481688-1360eca9-1edc-47da-a0a9-f7e433648586.png)

Shall we keep this issue open until this issue is resolved, or should we close this and let this be tracked in #374? @zainfathoni @mazipan

**Comment by zainfathoni** [comment]
Let's keep it open and add #374 as a task in this epic, since we can track the same issue in multiple epics.
