### ISSUE TITLE
SW activation and cache static files

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#637]
## Description

We have some static files those safe to be cache on the client side.

## Implementation Model

We can use [next-pwa](https://github.com/shadowwalker/next-pwa)

To be cache:

- All hashed CSS and JS - StaleWhileRevalidate/CacheFirst
- All Cloudinary image - CacheFirst with 30d expiry

DO NOT cache any HTML files

## Tasks

- [ ] Install `next-pwa`
- [ ] Add the next-pwa configuration on seperate file: `workbox.config.js`
- [ ] Link to the `next.config.js`
- [ ] Custom Install Button -- optional

**Comment by resir014** [comment]
Reopening this because we had to take out service worker due to #716.
