### ISSUE TITLE
Add more page on Web Perf Check Action

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#638]
## Description

Currently, we only test homepage on the LH-CI.
Maybe we can start to add another important pages.

The candidates:

- https://www.wargabantuwarga.com/faq
- https://www.wargabantuwarga.com/provinces
- https://www.wargabantuwarga.com/tentang-kami
- https://www.wargabantuwarga.com/donasi

## Implementation Model

Update `lighthouse-ci.yml` and `lighthouse-ci-prod.yml`.

The `--url` arguments can accept multiple parameters.

e.g: 

```shell
lhci collect --url=https://www.wargabantuwarga.com/ --url=https://www.wargabantuwarga.com/faq
```

## Tasks

- [ ] Update `lighthouse-ci.yml`
- [ ] Test the action with adding `need-perf-check` on the PR
- [ ] Apply to `lighthouse-ci-prod.yml`
