### ISSUE TITLE
Capability to open new tab on Homepage icon

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#654]
## Description

Based on issue #321 and PR #643, we add new icon 'kontribusi" which should be redirected to external URL.

The default behaviour is we need to open it on the new tab with proper `rel` attribute value.

## Tasks

- [ ] Add new `external` field on the icon list
- [ ] Handle properly for icons w `external: true`
- [ ] Open in new tab with `nofollow noreferrer noopener`
