### ISSUE TITLE
Replace Donasi Page thumbnail image using our own Cloudinary

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#665]
## Description

Donasi page still using external image, so we can not use the power of next/image, that's why the image will be loaded on the first load and have no optimization in term of dimension, quality and extension

![Screen Shot 2021-08-12 at 21 58 39](https://user-images.githubusercontent.com/7221389/129219766-59b0e6ae-defb-4d69-a7e6-968adf5d1172.png)

## Tasks

- [x] Ask @resir014, @zainfathoni, or @mazipan to upload the image to Cloudinary
- [x] Get the image and update it on CMS
- [x] Replace code implementation using `next/image`

## Images need to be uploaded

|  No  |  Current Image  |  Title | Cloudinary Image  |  
|-----|-----------------|------|-------------------|
| 1. | [Download here](https://imgix.kitabisa.com/ab30a32d-d156-430a-8924-eb158d839915.jpg?ar=16:9&w=664&auto=format,compress)  | Donasi untuk berbagai kebutuhan (RS, puskesmas, nakes, dan warga terdampak) | Please put here  | 
| 2.  |  [Download here](https://imgix.kitabisa.com/cd48addb-0567-46de-b4a7-f98e68b1cb70.jpg?ar=16:9&w=664&auto=format,compress)  | Donasi untuk Inisiatif #WargaBantuWarga | Please put here  | 
| 3.  | [Download here](https://www.wargabantuwarga.com/images/indonesia-pasti-bisa.png)   | Donasi untuk Penyediaan Oksigen Concentrators di Rumah Sakit | Please put here  | 
| 4.  | [Download here](https://imgix.kitabisa.com/2f5b4184-9be5-4c7d-ad8e-d4e0eab2c3de.jpg?ar=16:9&w=664&auto=format,compress)   | Donasi untuk Relawan dan Penggali Kubur | Please put here  | 
| 5.  | [Download here](https://imgix.kitabisa.com/4bd347ef-fd19-4909-9107-45d5b22f98ae.jpg?ar=16:9&w=664&auto=format,compress)   | Donasi untuk Warga dan Paket Isolasi Mandiri | Please put here  | 
| 6.  | [Download here](https://imgix.kitabisa.com/d79c0c3a-b958-4d4a-9b8c-5a19286f0242.jpg?ar=16:9&w=664&auto=format,compress)   | Donasi untuk Tenaga Kesehatan | Please put here  | 
| 7.  | [Download here](https://fastcdn.benihbaik.com/campaign/thumbnail/benihbaik_2021-07-27_1627376657_PT_60ffcc1149ca2.jpg)   | Donasi Paket Obat Gratis | Please put here  | 
| 8.  | [Download here](https://donasi.dompetdhuafa.org/wp-content/themes/donasidd/assets/img/logo-dd-with-text.png)   | Donasi via Dompet Dhuafa | Please put here  |

**Comment by mazipan** [comment]
I will help to upload it, I already got access to upload it.
Wait ya...

**Comment by hanihusam** [comment]
> I will help to upload it, I already got access to upload it.
> Wait ya...

Mas Irfan, have you uploaded the image yet?

**Comment by mazipan** [comment]
Yes, the data on the JSON already coming from our WBW Cloudinary
