### ISSUE TITLE
Build a mobile-first responsive design for Warga Bantu Warga

### ISSUE THREAD

**Issue by baraeb92** [kawalcovid19/wargabantuwarga.com#68]
## Overview

Description

 As a user who uses the mobile browser to visit the website I want all important information on the web to be mobile friendly so I can easily be accessing it using my relatively small mobile screen size, per instruction here: [https://material.io/design/layout/responsive-layout-grid.html#columns-gutters-and-margins](https://material.io/design/layout/responsive-layout-grid.html#columns-gutters-and-margins)

## Acceptance Criteria

 “Given a user that mainly browses using a mobile browser, when I visited the WargaBantuWarga website and click on google sheet link then the information is displayed in a mobile-friendly way that at least scored 90 on the accessibility score at web.dev audit” 

See guidelines here: https://web.dev/accessible/ and https://tailwindcss.com/docs/responsive-design

Also, please use the following resources to ensure easier component building and design consistency: 

- https://tailwindui.com/#components
- https://www.heropatterns.com/
- https://headlessui.dev/
- https://heroicons.com/
- https://www.figma.com/community/file/958381589801778722

## Require A QA To Test? 

yes

## Requirement

List all requirements that necessary to be detailed in the ticket

- [x] Create the design using [mobile-first responsive design principles](https://www.uxpin.com/studio/blog/a-hands-on-guide-to-mobile-first-design/)
- [x] Enable text compression and make sure that font is visible during load
- [x] Make sure all button or interactive element size is at least 48x48px

## Current tasks

- [x] #87
- [x] #92 
- [x] #104 
- [x] #122
- [x] #127
- [x] #174
- [x] #241
