### ISSUE TITLE
Add Officially Supported Apps section in homepage

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#710]
## Description

Related with #668, we need to create new section to replace "Officially Supported Apps by Kemenkes" in our homepage

![Screen Shot 2021-08-13 at 22 35 42](https://user-images.githubusercontent.com/7221389/129383562-471eba41-7168-4a82-97f7-8a588ef08ad4.png)

## Figma

https://www.figma.com/file/XNNtIoFEdFqaXOee83n0oN/WBW?node-id=458%3A1634

## Implementation Model

The data will be placed on CMS

## Tasks

- [ ] Add new CMS collection #706
- [ ] Add new section on homepage
- [ ] Reorder the section on homepage: Telemedicine CTA > Official Apps > Hotline

**Comment by ryanadhi** [comment]
@mazipan 
do we need to remove this part from homepage and replace it with the one from [Figma](https://www.figma.com/file/XNNtIoFEdFqaXOee83n0oN/WBW?node-id=458%3A1972)? 
![Screenshot 2021-08-14 220952](https://user-images.githubusercontent.com/35433920/129450797-91928580-417d-41cd-937f-c59da25d024d.png)

**Comment by zainfathoni** [comment]
Yes, exactly, @ryanadhi.

You can start working on the UI parts now and integrate with #706 once it's merged.
Please create a [draft pull request](https://kcov.id/draft-pr) as soon as you have your first commit.
Thanks!

**Comment by mazipan** [comment]
Yes, I am still working on the CMS part.
But still have no time to continue.
Will do tomorrow, but the initial data is already on master.
I will let you know when I made changes related this ticket.

**Comment by zainfathoni** [comment]
> Yes, I am still working on the CMS part.
> 
> But still have no time to continue.
> 
> Will do tomorrow, but the initial data is already on master.
> 
> I will let you know when I made changes related this ticket.

There's a draft pull request on #733 already, Mas @mazipan. I think you can focus on some other issues instead. 😁

**Comment by mazipan** [comment]
No, I only work on the CMS part. Not the UI

**Comment by mazipan** [comment]
I only work on the CMS configuration.
No additional changes.
