### ISSUE TITLE
Konseling Page

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#712]
## Description

![Screen Shot 2021-08-13 at 23 01 20](https://user-images.githubusercontent.com/7221389/129387069-4a1cccd7-d8ae-4573-a757-c9596b486110.png)

## Figma

https://www.figma.com/file/XNNtIoFEdFqaXOee83n0oN/WBW?node-id=458%3A1634

## Data Source

https://docs.google.com/spreadsheets/d/1JRlBNwmqoVimwR70dwIVJ1QAnBbC0Mqp0DmomeO0cWU/edit#gid=0

## Tasks

- [ ] Create new collection on CMS
- [ ] Move the data to CMS
- [ ] Create new page
- [ ] Entry Point -- Need help from Design Team @zainfathoni
