### ISSUE TITLE
Explain our use of Conventional Commits in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/wargabantuwarga.com#744]
## Description

This repository uses the Conventional Changelog specification for our commit messages + Pull Request titles. Explain in the `CONTRIBUTING.md` file about how we use these commit messages.

## Implementation model

The Conventional Changelog specification can be read here: https://www.conventionalcommits.org/en/v1.0.0/ - as a refresher:

```
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
```

The commit types that we use are: `feat`, `fix`, `refactor`, `docs`, `build`, `chore`, `perf`, `style`, `test`. This follows the [Angular commit message guidelines](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type).

If possible, we should also define the **scopes** that this project uses.

## Tasks

- [ ] Explain our use of Conventional Changelog specification
- [ ] Explain the commit types that we use
- [ ] Explain the use of [commitlint](https://commitlint.js.org/#/) to lint commit messages
- [x] (Optional) Switch default merge type for PRs to squash merge-only, to ensure all commit messages match standards

**Comment by resir014** [comment]
Final task has already done through the GitHub repo settings.

![image](https://user-images.githubusercontent.com/5663877/129547861-d44b5bc0-01af-4524-9797-333d2f658e35.png)

We can update each PR's title with the appropriate conventional commit standards before triggering automerge.
