### ISSUE TITLE
Database Schema Migration

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#783]
### Problem Statement

The current workflow of our database management system is too complicated and has a significant bottleneck in the manual update process. This situation hinders us from scaling up our database updater volunteers.

<img width="901" alt="Screenshot 2021-08-30 at 22 02 13" src="https://user-images.githubusercontent.com/6315466/131351528-8aa6b25b-3e9a-4393-ac84-528360c9f567.png">

### Solution

Therefore, we came up with a more scalable database management system.

<img width="1117" alt="Screenshot 2021-08-30 at 22 03 10" src="https://user-images.githubusercontent.com/6315466/131351660-b169d292-52f6-4923-99fe-703c64ebcbbc.png">

### Implications to the Website

1. The main Google Sheets file needs to be moved into another file
2. There are additional columns to operate with
3. `Tanggal Verifikasi` is not to be shown on the website anymore. Only the `Terakhir Update` field is shown.
4. `Tanggal Verfikasi` only impacts the ✅ checkmark status on the website.

### More Context

Three weeks ago, we initiated a discussion on [this Slack thread](https://kawalcovid19.slack.com/archives/C0279E2Q99Q/p1628570911020800) where we defined the problem statements and the potential solutions here: [Penyesuaian Workflow dan Database Relawan](https://docs.google.com/document/d/1wZr-ATaO-CwAjeUajppz2u5irH9t_xRoio3RtwJZEFA/edit?usp=sharing).

<img width="452" alt="Screenshot 2021-08-30 at 21 51 15" src="https://user-images.githubusercontent.com/6315466/131349923-3b95a5e1-9ac1-49ed-a525-9905530516ec.png">

Two weeks ago, the [new database schema](https://docs.google.com/document/d/1sirQvJqDoq9lcgcqBtX8PkjdUrygI9K8-s_E4_Ld964/edit#heading=h.s7zyjnpztyl) was [ready to implement](https://docs.google.com/spreadsheets/d/1SRByPnPalzDHgo5RM85yv2V_N8Z-OylBbIgrre_xwg0/edit#gid=0), but I couldn't afford to spend enough focus on this issue because we had to focus on kawalcovid19/silacak#8 for a few weeks.

<img width="438" alt="Screenshot 2021-08-30 at 21 52 30" src="https://user-images.githubusercontent.com/6315466/131350109-4a1901fc-7037-4e46-899c-a8de361bc0b7.png">

Since we have deprioritised kawalcovid19/silacak#8 for now, we can resume our focus on this issue.

## Current Tasks

These are the tasks we need to do to migrate the content gracefully. Please always refer to these documents to understand the expected result of the new database schema:

1. [Struktur Informasi Baru Database WBW](https://docs.google.com/document/d/1sirQvJqDoq9lcgcqBtX8PkjdUrygI9K8-s_E4_Ld964/edit?usp=sharing).
2. [[Database Utama] WargaBantuWarga](https://kcov.id/wbw-database)

- [ ] Implement `fetch-database.ts` to fetch from https://kcov.id/wbw-database
- [ ] Use `fetch-database.ts` in `mirror-box.ts`
- [ ] Write e2e tests to ensure there are no regressions introduced during the database migration
- [ ] Use the `wbw-database.json` data in the `Province` and `Contact` page according to the new logic
