### ISSUE TITLE
Migrate vaccination data to the official API from Kemenkes

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#802]
### Problem Statement

Due to the reduced urgency of frequent data updates, we have decommissioned our database updater volunteers for https://kcov.id/wbw-database. On the other side, the Kemenkes team has provided an API endpoint documented at https://api.vaksinasi.id/docs, with the data sourced from our active volunteers.

### Solution

We need to replace our vaccination data from https://kcov.id/wbw-database with the latest data https://api.vaksinasi.id/docs.

It will affect the `Tempat vaksin` category in our provinces database, e.g. https://www.wargabantuwarga.com/provinces/dki-jakarta?kebutuhan=Tempat%20vaksin

## Current Tasks

- [ ] Implement `fetch-vaccination-database.ts` to fetch data from https://api.vaksinasi.id/docs and store it into `wbw-vaccination-database.json` file
- [ ] Use `fetch-vaccination-database.ts` in `mirror-box.ts`
- [ ] #786
- [ ] Use the `wbw-vaccination-database.json` data to replace all `Tempat vaksin` data from `wbw-database.json`
