### ISSUE TITLE
FAQ page enhancements

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#93]
## Overview

We have finished our basic functionalities for the [FAQ page](https://www.wargabantuwarga.com/faqs).

## Current Tasks

- [ ] Rename the FAQ page path from `/faqs` into `/faq`
- [ ] Reuse `useSearch` custom hook and `SearchForm` component in the FAQ page
- [ ] Implement filter dropdown based on `Kategori Pertanyaan`
