### ISSUE TITLE
Speed up contributors onboarding

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#99]
## Overview

Update [CONTRIBUTING.md](https://github.com/kawalcovid19/wargabantuwarga.com/blob/2d11753fd98ad2b3b653e5eab7563eff08335510/CONTRIBUTING.md#L5) with more detailed instructions make onboarding our contributors easier.

## Current Tasks

These are the aspects that we need to cover to ease onboarding our contributors.

- [ ] Explain how we utilise [Draft Pull Requests](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) to communicate each other (with screenshots)
- [ ] Explain what the [Kanban Board](https://github.com/kawalcovid19/wargabantuwarga.com/projects/1) and the [Prioritization](https://github.com/kawalcovid19/wargabantuwarga.com/projects/2) projects mean
- [ ] Explain how to utilise the [Labels](https://github.com/kawalcovid19/wargabantuwarga.com/labels) effectively
- [ ] Explain what our [Milestones](https://github.com/kawalcovid19/wargabantuwarga.com/milestones) for the next few months
